---

linters:
# Newline at end of file required when enabled
  FinalNewline:
    enabled: true
    
# Check content style  
  ContentStyle:
    enabled: true
    addendum: "Questions? Contact #product-content on Slack or @Shopify/product-content on GitHub."
    rule_set:
    
      - violation: ['[Dd]ropdown menu', '[Dd]rop down menu']
        suggestion: 'drop-down menu'
        violation_condensed: "dropdown menu/drop down menu"
      - violation: ['^((?!Shopify Help Center).)*[Hh]elp [Cc]enter']
        suggestion: 'Shopify Help Center'
        violation_condensed: 'help center'
      - violation: ['lite plan', '[Ll]ight [Pp]lan']
        suggestion: 'Lite plan'
        violation_condensed: "lite plan/light plan"
        
# Check for deprecated classes        
  DeprecatedClasses:
      enabled: true
      addendum: "If you’re having trouble feel free to reach out to #admin-fed."
      rule_set:
        #########################################################################################
        # Old Classes --> Components                                                            #
        #########################################################################################
  
        # Badge classes (app/assets/stylesheets/ui-kit/components/_badge.scss)
        - deprecated: ['badge[-_\w]*']
          suggestion: "Use the Badge Component (styleguide.myshopify.com/components/badge)."
