---

linters:
  FinalNewline:
    enabled: true
  ContentStyle:
    enabled: true
    addendum: "Questions? Contact #product-content on Slack or @Shopify/product-content on GitHub."
    rule_set:
      - violation: '[Bb]uy button'
        suggestion: 'Shopify Buy Button'
